package com.adverity

class Utility {

    static List<String> sources = [ "Google Ads", "Facebook Ads", "Twitter Ads" ]
    static List<String> campaigns = ["DE|SN|Snow Bindungen|Brands",
                              "SN_OnlineSchnäppchen_Leuchtenwald",
                              "Motorrad Mitgliedschaft",
                              "Touring-Set",
                              "SN_OnlineSchnäppchen_Philips Schallzahnbürste",
                              "Carfinder",
                              "DE|SN|Skate|Generisch",
                              "DE|SN|Snow Schuhe|Brands",
                              "Online-Special_Trendwizzard Fahrrad",
                              "SN_Wettbewerber",
                              "US|SN|Amazon",
                              "SN_OnlineSchnäppchen_Krups Wasserkocher",
                              "AT|SN|Snowboards|Brands",
                              "Firmen Mitgliedschaft",
                              "ÖAMTC App|In-App",
                              "SN_Kistenkonkurrenz",
                              "SN_OnlineSchnäppchen_Philips_Airfryer",
                              "SN_Brand Produkte",
                              "SN_OnlineSchnäppchen_Krups Toaster",
                              "DE|SN|Snow Helme|Brands",
                              "Pickerl-Erinnerung",
                              "AT|SN|Snow Jacken|Brands",
                              "SN_OnlineSchnäppchen_Kaffeepadmaschine",
                              "Adventmarkt Touristik",
                              "Touristik City Guide",
                              "AT|SN|Skate|Generisch",
                              "Vorteilspartner",
                              "SN_KochAbo",
                              "Touristik City Guide_iOS",
                              "DE | SP Gadgets",
                              "Nothilfe|Tablets iOS",
                              "DE|SN|Skullcandy",
                              "AT|SN|Snow Helme|Brands",
                              "SN_OnlineSchnäppchen_AEG_Staubsauger",
                              "SN_Lebensmittel",
                              "ÖAMTC App",
                              "ÖAMTC App|Smartphones iOS",
                              "AT|SN|Snow Hosen|Brands",
                              "AT|SN|Snow Schuhe|Brands",
                              "Rechtsschutz",
                              "SN_Online-Special_Esprit Buggy",
                              "AT|SN|Snowboard|Generisch",
                              "ÖAMTC App|Smartphones Android",
                              "SN_OnlineSchnäppchen_Saeco_Kaffeevollautomat",
                              "DE|SN|Snow Jacken",
                              "AT|SN|Longboard|Generisch",
                              "Nulltarif-Q4",
                              "Versicherungen",
                              "Freundschaftswerbung",
                              "NT ÖCC",
                              "Schutzbrief Image|SN",
                              "SN_Brand",
                              "Touristik City Guide_Android",
                              "DE | PLA",
                              "SN_Hüttengaudi_Felicity Filztaschen",
                              "Nothilfe|Smartphones iOS",
                              "SN_OnlineSchnäppchen_Philips_Tischgrill",
                              "Remarketing",
                              "DE|SN|Snow Hosen|Brands",
                              "SN_OnlineSchnäppchen_Trendline Kaltschaummatratze",
                              "Rechtsschutz - MOBIL",
                              "GDN_Retargeting",
                              "WRKS",
                              "SN_Essen",
                              "DE|SN|Snowboards|Brands",
                              "RM|SP Gadgets",
                              "ÖCC",
                              "DE|SN|Wear|Brands",
                              "SN_OnlineSchnäppchen_Tefal Raclette-Grill",
                              "SN_OnlineSchnäppchen_LG Heimkinoanlage",
                              "AT|SN|Skullcandy",
                              "Nothilfe|Tablets Android",
                              "AT | PLA",
                              "AT|SN|Brand",
                              "Schutzbrief",
                              "Mitgliedschaft KiMi",
                              "Google Shopping",
                              "Touristik Routenplaner",
                              "SN_Obstbox",
                              "DE|SN|Splitboard|Brands",
                              "EN | SP Gadgets",
                              "AT|SN|Snow Bindungen|Brands",
                              "ÖAMTC ADAM-MANIA Gewinnspiel",
                              "ÖAMTC Autopreis Marcus 2014",
                              "Schutzbrief Image|DN",
                              "SN_Online-Special_Dyson Staubsauger",
                              "DE|SN|Snowboard|Generisch",
                              "SN_OnlineSchnäppchen_Gaggia_Espressosiebträger",
                              "AT|SN|Splitboard|Brands",
                              "DE|SN|Brand",
                              "Führerschein-Test",
                              "SN_Partner",
                              "SN_Online-Special_LG Fernseher",
                              "ÖAMTC App|Tablets iOS",
                              "SN_Online-Only_Kochtopfset",
                              "SN_OnlineSchnäppchen_Philips Küchenmaschine",
                              "Nothilfe|Smartphones Android",
                              "DE|SN|Longboard|Generisch",
                              "Bonus Kasko",
                              "ÖAMTC App|Tablets Android",
                              "SN_Specials",
                              "Nulltarif",
                              "Nothilfe",
                              "SN_OnlineSchnäppchen_Gorenje Mikrowelle"]

}
